# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path

ROOT = Path(SPECPATH).parent

a = Analysis(
    [str(ROOT / 'src' / 'sheetsync_desktop.py')],
    pathex=[str(ROOT / 'src')],
    binaries=[],
    datas=[
        (str(ROOT / 'src' / 'sheetsync' / 'ui'), 'sheetsync/ui'),
        (str(ROOT / 'assets'), 'assets'),
    ],
    hiddenimports=[
        'sheetsync',
        'sheetsync.api',
        'sheetsync.core',
        'sheetsync.core.google_auth',
        'sheetsync.core.storage',
        'sheetsync.core.syncer',
        'sheetsync.core.tray',
        'sheetsync.core.watcher',
        'webview',
        'webview.platforms',
        'webview.platforms.winforms',
        'webview.util',
        'pystray',
        'pystray._win32',
        'PIL',
        'PIL.Image',
        'clr',
        'clr_loader',
        'pythonnet',
        'gspread',
        'google.auth',
        'google.auth.transport.requests',
        'google.oauth2.credentials',
        'google_auth_oauthlib.flow',
        'openpyxl',
        'watchdog',
        'watchdog.observers',
        'watchdog.events',
        'plyer',
        'plyer.platforms.win.notification',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['flet', 'flet_core', 'flet_desktop'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SheetSync',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / 'assets' / 'icons' / 'app.ico'),
)
